import { pgTable, text, integer, real, boolean, jsonb, serial, primaryKey } from "drizzle-orm/pg-core";

// ── Fully Normalized Tables ────────────────────────────────────────────────

/**
 * Customers table.
 * IDs follow the pattern `cust_<timestamp>_<random>` as generated by
 * the existing Zustand store (customerStore.ts).
 */
export const customers = pgTable("customers", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  company: text("company"),
  email: text("email"),
  phone: text("phone"),
  address: text("address"),
  notes: text("notes"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

/**
 * Quotes table.
 * customerSnapshot is stored as a JSON blob (name, company, email, phone)
 * so that the quote remains self-contained even if the customer is later deleted.
 */
export const quotes = pgTable("quotes", {
  id: text("id").primaryKey(),
  number: integer("number").notNull().unique(),
  title: text("title").notNull(),
  customerId: text("customer_id").references(() => customers.id, {
    onDelete: "set null",
  }),
  customerSnapshot: jsonb("customer_snapshot"),
  globalDiscountPercent: real("global_discount_percent").default(0),
  subtotal: real("subtotal").default(0),
  discountAmount: real("discount_amount").default(0),
  total: real("total").default(0),
  status: text("status", {
    enum: ["draft", "sent", "approved", "rejected"],
  }).default("draft"),
  validUntil: text("valid_until").notNull(),
  paymentTerms: text("payment_terms").default(""),
  deliveryEstimate: text("delivery_estimate").default(""),
  footerNote: text("footer_note"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
  exportedAt: integer("exported_at"),
});

/**
 * Quote items (line items).
 * Each item links back to a history entry (for cost data) and to a quote.
 */
export const quoteItems = pgTable("quote_items", {
  id: serial("id").primaryKey(),
  quoteId: text("quote_id")
    .notNull()
    .references(() => quotes.id, { onDelete: "cascade" }),
  historyEntryId: text("history_entry_id").notNull(),
  name: text("name").notNull(),
  quantity: integer("quantity").default(1),
  unitPrice: real("unit_price").default(0),
  totalPrice: real("total_price").default(0),
  discountPercent: real("discount_percent").default(0),
});

/**
 * History entries — saved calculation results.
 * resultJson holds the full CalculationResult object.
 * snapshotJson holds the CalculationSnapshot (all calculator inputs).
 */
export const historyEntries = pgTable("history_entries", {
  id: text("id").primaryKey(),
  timestamp: integer("timestamp").notNull(),
  type: text("type", { enum: ["fdm", "resin"] }).notNull(),
  name: text("name").notNull(),
  summary: text("summary").default(""),
  totalCost: real("total_cost").default(0),
  sellPrice: real("sell_price").default(0),
  profit: real("profit").default(0),
  resultJson: jsonb("result_json").notNull(),
  snapshotJson: jsonb("snapshot_json"),
});

/**
 * Filament spools — inventory tracking.
 */
export const filamentSpools = pgTable("filament_spools", {
  id: text("id").primaryKey(),
  brand: text("brand").default(""),
  material: text("material").default("PLA"),
  color: text("color").default(""),
  colorHex: text("color_hex").default(""),
  weightGrams: real("weight_grams").default(0),
  originalWeightGrams: real("original_weight_grams").default(1000),
  costPerKg: real("cost_per_kg").default(0),
  diameterMm: real("diameter_mm").default(1.75),
  dateAdded: integer("date_added").notNull(),
  notes: text("notes").default(""),
  status: text("status", { enum: ["in_stock", "on_the_way", "empty"] }).default(
    "in_stock",
  ),
  purchaseStore: text("purchase_store").default(""),
  tareGrams: real("tare_grams"),
});

/**
 * Built-in printer catalog.
 * Seeded from printers-database.json / printers.ts.
 */
export const catalogPrinters = pgTable("catalog_printers", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  brand: text("brand").notNull(),
  power: real("power").notNull(),
  value: real("value").notNull(),
  usefulLife: integer("useful_life").notNull(),
  maintenancePerHour: real("maintenance_per_hour").notNull(),
  image: text("image"),
  maxFilaments: integer("max_filaments"),
  custom: boolean("custom").default(false),
});

/**
 * Built-in material catalog.
 */
export const catalogMaterials = pgTable("catalog_materials", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  density: real("density").notNull(),
  avgPrice: real("avg_price").notNull(),
  type: text("type", { enum: ["fdm", "resin"] }).notNull(),
  custom: boolean("custom").default(false),
});

/**
 * Built-in marketplace catalog.
 */
export const catalogMarketplaces = pgTable("catalog_marketplaces", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  feePercent: real("fee_percent").notNull(),
  feeFixed: real("fee_fixed").notNull(),
  hasFreeShipping: boolean("has_free_shipping").default(false),
  shippingFeePercent: real("shipping_fee_percent"),
  custom: boolean("custom").default(false),
});

/**
 * Products — standalone sale inventory (Issue #68).
 * IDs follow the pattern `prod_<timestamp>_<random>` as generated by
 * the Zustand store (productInventory.ts). No foreign keys: products are
 * self-contained (sold flag is toggled manually, never derived).
 */
export const products = pgTable("products", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  weightGrams: real("weight_grams").default(0),
  filamentType: text("filament_type").default(""),
  costPrice: real("cost_price").default(0),
  salePrice: real("sale_price").default(0),
  sold: boolean("sold").default(false),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

// ── JSON Blob / Key-Value Tables ──────────────────────────────────────────

/**
 * Single-row table for the entire calculator state.
 * The CHECK(id = 1) constraint ensures only one row exists.
 */
export const calculatorState = pgTable("calculator_state", {
  id: integer("id").primaryKey().default(1),
  stateJson: jsonb("state_json").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

/**
 * Key-value store for app settings:
 * - consent (GDPR / cookie consent)
 * - tutorial (completed flag)
 * - dashboard prefs
 * - onboarding flag
 * - currency setting
 */
export const appSettings = pgTable("app_settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
});

/**
 * Generic key-value storage for IPC persistence layer.
 * Used by the StoragePort adapter to replace localStorage.
 * Maps 1:1 with the existing localStorage keys:
 * open3dcalc_settings_v2, open3dcalc_history_v2,
 * open3dcalc_quotes_v1, open3dcalc_customers_v1, etc.
 */
export const storage = pgTable("storage", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  updatedAt: integer("updated_at").notNull(),
});

// ── Inferred Types ─────────────────────────────────────────────────────────

export type Customer = typeof customers.$inferSelect;
export type NewCustomer = typeof customers.$inferInsert;

export type Quote = typeof quotes.$inferSelect;
export type NewQuote = typeof quotes.$inferInsert;

export type QuoteItem = typeof quoteItems.$inferSelect;
export type NewQuoteItem = typeof quoteItems.$inferInsert;

export type HistoryEntry = typeof historyEntries.$inferSelect;
export type NewHistoryEntry = typeof historyEntries.$inferInsert;

export type FilamentSpool = typeof filamentSpools.$inferSelect;
export type NewFilamentSpool = typeof filamentSpools.$inferInsert;

export type Product = typeof products.$inferSelect;
export type NewProduct = typeof products.$inferInsert;

export type CatalogPrinter = typeof catalogPrinters.$inferSelect;
export type NewCatalogPrinter = typeof catalogPrinters.$inferInsert;

export type CatalogMaterial = typeof catalogMaterials.$inferSelect;
export type NewCatalogMaterial = typeof catalogMaterials.$inferInsert;

export type CatalogMarketplace = typeof catalogMarketplaces.$inferSelect;
export type NewCatalogMarketplace = typeof catalogMarketplaces.$inferInsert;

export type CalculatorState = typeof calculatorState.$inferSelect;
export type NewCalculatorState = typeof calculatorState.$inferInsert;

export type AppSetting = typeof appSettings.$inferSelect;
export type NewAppSetting = typeof appSettings.$inferInsert;

export type StorageRow = typeof storage.$inferSelect;
export type NewStorageRow = typeof storage.$inferInsert;

// ── PII Infrastructure Tables ─────────────────────────────────────────────

/**
 * PII stage table — holds encrypted preimages during re-homing.
 * Composite PK: (transaction_id, generation).
 * See migration 0004 for full design rationale.
 */
export const piiStage = pgTable("pii_stage", {
  transactionId: text("transaction_id").notNull(),
  generation: integer("generation").notNull(),
  privacyEpoch: integer("privacy_epoch").notNull(),
  schemaVersion: integer("schema_version").notNull(),
  envelopeVersion: integer("envelope_version").notNull(),
  state: text("state").notNull(),
  blob: text("blob").notNull(),
  createdAt: integer("created_at").notNull(),
}, (table) => ({
  pk: primaryKey({ columns: [table.transactionId, table.generation] }),
}));

/**
 * Legacy ciphertext residue — retained copies of re-sealed values.
 * See migration 0005 for full design rationale.
 */
export const legacyResidue = pgTable("legacy_residue", {
  key: text("key").primaryKey(),
  shape: text("shape").notNull(),
  blob: text("blob").notNull(),
  recoveredValueSha: text("recovered_value_sha").notNull(),
  recoveredAt: integer("recovered_at").notNull(),
});

export type PiiStage = typeof piiStage.$inferSelect;
export type NewPiiStage = typeof piiStage.$inferInsert;
export type LegacyResidue = typeof legacyResidue.$inferSelect;
export type NewLegacyResidue = typeof legacyResidue.$inferInsert;